name = "TikzGenerator"
uuid = "23a9c889-7444-45b7-9f69-4f5454fff3e9"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MatchCore = "5dd3f0b1-72a9-48ad-ae6e-79f673da005f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
